/**
 * Lezer grammar entry point for the httui HTTP fence dialect.
 *
 * Consumers (typically the CodeMirror 6 client in the httui desktop app)
 * import the `parser` and wire it into a CM6 language extension to get
 * lexical first-paint highlighting of ```http fence bodies.
 */

import { LRParser } from "@lezer/lr";
import { styleTags, tags, Tag } from "@lezer/highlight";
// The parser file is generated by `lezer-generator` from src/http.grammar
// at build time (see package.json `build:parser` script). It is not
// committed; CI and `npm install` regenerate it.
// @ts-expect-error — generated at build time
import { parser as generatedParser } from "./parser.js";

const method = Tag.define(tags.keyword);

/** Highlight tags for the HTTP fence dialect.
 *
 * Every tag derives from a standard `@lezer/highlight` tag, so themes
 * that only know the standard set still get sensible colors; consumers
 * wanting per-method colors target the specific tags.
 */
export const httpTags = {
  method,
  methodGet: Tag.define(method),
  methodPost: Tag.define(method),
  methodPut: Tag.define(method),
  methodPatch: Tag.define(method),
  methodDelete: Tag.define(method),
  methodHead: Tag.define(method),
  methodOptions: Tag.define(method),
  url: Tag.define(),
  headerName: Tag.define(tags.propertyName),
  headerValue: Tag.define(tags.string),
  queryLine: Tag.define(tags.attributeValue),
  descLine: Tag.define(tags.docComment),
  commentLine: Tag.define(tags.comment),
  disabledLine: Tag.define(tags.comment),
};

export const parser: LRParser = (generatedParser as LRParser).configure({
  props: [
    styleTags({
      GET: httpTags.methodGet,
      POST: httpTags.methodPost,
      PUT: httpTags.methodPut,
      PATCH: httpTags.methodPatch,
      DELETE: httpTags.methodDelete,
      HEAD: httpTags.methodHead,
      OPTIONS: httpTags.methodOptions,
      Method: httpTags.method,
      Url: httpTags.url,
      HeaderName: httpTags.headerName,
      HeaderValue: httpTags.headerValue,
      QueryLine: httpTags.queryLine,
      DescLine: httpTags.descLine,
      CommentLine: httpTags.commentLine,
      "DisabledQueryLine DisabledHeaderLine": httpTags.disabledLine,
    }),
  ],
});
