/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_method = 1,
  sym_url = 2,
  sym_query_line = 3,
  anon_sym_COLON = 4,
  sym_header_name = 5,
  sym_header_value = 6,
  sym_desc_line = 7,
  sym_disabled_query_line = 8,
  sym_disabled_header_line = 9,
  sym_comment_line = 10,
  sym_body_line = 11,
  sym__newline = 12,
  sym__blank = 13,
  sym_source_file = 14,
  sym_request_line = 15,
  sym_header_line = 16,
  sym_body = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_source_file_repeat2 = 19,
  aux_sym_body_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_method] = "method",
  [sym_url] = "url",
  [sym_query_line] = "query_line",
  [anon_sym_COLON] = ":",
  [sym_header_name] = "header_name",
  [sym_header_value] = "header_value",
  [sym_desc_line] = "desc_line",
  [sym_disabled_query_line] = "disabled_query_line",
  [sym_disabled_header_line] = "disabled_header_line",
  [sym_comment_line] = "comment_line",
  [sym_body_line] = "body_line",
  [sym__newline] = "_newline",
  [sym__blank] = "_blank",
  [sym_source_file] = "source_file",
  [sym_request_line] = "request_line",
  [sym_header_line] = "header_line",
  [sym_body] = "body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_method] = sym_method,
  [sym_url] = sym_url,
  [sym_query_line] = sym_query_line,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name] = sym_header_name,
  [sym_header_value] = sym_header_value,
  [sym_desc_line] = sym_desc_line,
  [sym_disabled_query_line] = sym_disabled_query_line,
  [sym_disabled_header_line] = sym_disabled_header_line,
  [sym_comment_line] = sym_comment_line,
  [sym_body_line] = sym_body_line,
  [sym__newline] = sym__newline,
  [sym__blank] = sym__blank,
  [sym_source_file] = sym_source_file,
  [sym_request_line] = sym_request_line,
  [sym_header_line] = sym_header_line,
  [sym_body] = sym_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_query_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [sym_desc_line] = {
    .visible = true,
    .named = true,
  },
  [sym_disabled_query_line] = {
    .visible = true,
    .named = true,
  },
  [sym_disabled_header_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_body_line] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
  [sym_header_line] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '&' ||
          lookahead == '?') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(39);
      END_STATE();
    case 5:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '&' ||
          lookahead == '?') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(15);
      END_STATE();
    case 6:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 7:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(11);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_method);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_query_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ':') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_header_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_header_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_desc_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_disabled_query_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_disabled_header_line);
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_disabled_header_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead == '&' ||
          lookahead == '?') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 'c') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 's') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == ':') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == 'c') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == 'd') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == 's') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__blank);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_method] = ACTIONS(1),
    [sym_query_line] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_desc_line] = ACTIONS(1),
    [sym_disabled_query_line] = ACTIONS(1),
    [sym_disabled_header_line] = ACTIONS(1),
    [sym_comment_line] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__blank] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym_request_line] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_method] = ACTIONS(5),
    [sym_desc_line] = ACTIONS(7),
    [sym_comment_line] = ACTIONS(9),
    [sym__newline] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(15), 1,
      sym_header_name,
    ACTIONS(19), 1,
      sym__newline,
    STATE(19), 1,
      sym_header_line,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(17), 2,
      sym_disabled_header_line,
      sym_comment_line,
    ACTIONS(13), 3,
      sym_query_line,
      sym_desc_line,
      sym_disabled_query_line,
  [23] = 6,
    ACTIONS(5), 1,
      sym_method,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_comment_line,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(11), 1,
      sym_request_line,
    ACTIONS(23), 2,
      sym_desc_line,
      sym__newline,
  [43] = 4,
    ACTIONS(32), 1,
      sym_comment_line,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      sym_method,
    ACTIONS(29), 2,
      sym_desc_line,
      sym__newline,
  [58] = 4,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_body_repeat1,
    STATE(23), 1,
      sym_body,
    ACTIONS(37), 2,
      sym_body_line,
      sym__newline,
  [72] = 4,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_body_repeat1,
    STATE(21), 1,
      sym_body,
    ACTIONS(37), 2,
      sym_body_line,
      sym__newline,
  [86] = 4,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym_body_repeat1,
    STATE(24), 1,
      sym_body,
    ACTIONS(37), 2,
      sym_body_line,
      sym__newline,
  [100] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym__newline,
    ACTIONS(45), 1,
      sym__blank,
    STATE(10), 1,
      aux_sym_source_file_repeat2,
  [113] = 3,
    ACTIONS(49), 1,
      sym_url,
    ACTIONS(51), 1,
      sym__newline,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      sym__blank,
  [124] = 4,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym__newline,
    ACTIONS(53), 1,
      sym__blank,
    STATE(15), 1,
      aux_sym_source_file_repeat2,
  [137] = 4,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym__newline,
    ACTIONS(53), 1,
      sym__blank,
    STATE(13), 1,
      aux_sym_source_file_repeat2,
  [150] = 3,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_body_repeat1,
    ACTIONS(57), 2,
      sym_body_line,
      sym__newline,
  [161] = 4,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym__newline,
    ACTIONS(59), 1,
      sym__blank,
    STATE(15), 1,
      aux_sym_source_file_repeat2,
  [174] = 3,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      sym_header_value,
    ACTIONS(65), 2,
      sym__newline,
      sym__blank,
  [185] = 3,
    ACTIONS(69), 1,
      sym__newline,
    STATE(15), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym__blank,
  [196] = 3,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_body_repeat1,
    ACTIONS(74), 2,
      sym_body_line,
      sym__newline,
  [207] = 2,
    ACTIONS(79), 1,
      sym__newline,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym__blank,
  [215] = 2,
    ACTIONS(83), 1,
      sym__newline,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym__blank,
  [223] = 2,
    ACTIONS(85), 1,
      sym__newline,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym__blank,
  [231] = 1,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
  [235] = 1,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
  [239] = 1,
    ACTIONS(89), 1,
      anon_sym_COLON,
  [243] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [247] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 43,
  [SMALL_STATE(5)] = 58,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 86,
  [SMALL_STATE(8)] = 100,
  [SMALL_STATE(9)] = 113,
  [SMALL_STATE(10)] = 124,
  [SMALL_STATE(11)] = 137,
  [SMALL_STATE(12)] = 150,
  [SMALL_STATE(13)] = 161,
  [SMALL_STATE(14)] = 174,
  [SMALL_STATE(15)] = 185,
  [SMALL_STATE(16)] = 196,
  [SMALL_STATE(17)] = 207,
  [SMALL_STATE(18)] = 215,
  [SMALL_STATE(19)] = 223,
  [SMALL_STATE(20)] = 231,
  [SMALL_STATE(21)] = 235,
  [SMALL_STATE(22)] = 239,
  [SMALL_STATE(23)] = 243,
  [SMALL_STATE(24)] = 247,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_line, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_line, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_httui_http(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "httui_http",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
