/**
 * Lezer grammar entry point for httui reference syntax.
 *
 * Consumers (typically the CodeMirror 6 client in the httui desktop app)
 * import the `parser` and wire it into a CM6 language extension to get
 * lexical first-paint highlighting of {{alias.path}} forms.
 */

import { LRParser } from "@lezer/lr";
// The parser file is generated by `lezer-generator` from src/refs.grammar
// at build time (see package.json `build:parser` script). It is not
// committed; CI and `npm install` regenerate it.
// @ts-expect-error — generated at build time
import { parser as generatedParser } from "./parser.js";

export const parser: LRParser = generatedParser;

/** Token kind names emitted by this grammar.
 *
 * These match the canonical vocabulary documented in
 * httui-lang/spec/token-kinds.md. Clients consuming this grammar map
 * Lezer node names to the corresponding kind for theming.
 */
export const TOKEN_KIND_MAP = {
  LBrace: "delimiter",
  RBrace: "delimiter",
  Dot: "punctuation",
  LBracket: "punctuation",
  RBracket: "punctuation",
  // Inside a Ref, the first Identifier is the alias (or env var).
  // Subsequent Identifiers (after a Dot) are ref_path segments.
  // The disambiguation requires walking the tree, not raw tokens — see
  // the highlight integration in the CM6 client.
  Identifier: "httui.alias",
  Number: "number",
} as const;
